/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 01:56:59 PM PDT 
//

package org.esipfed.eskg.structures;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Data_Center_Name"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Data_Center_URL" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Data_Set_ID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Personnel" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataCenterName",
    "dataCenterURL",
    "dataSetID",
    "personnel"
})
@XmlRootElement(name = "Data_Center")
public class DataCenter {

    @XmlElement(name = "Data_Center_Name", required = true)
    protected DataCenterName dataCenterName;
    @XmlElement(name = "Data_Center_URL")
    protected String dataCenterURL;
    @XmlElement(name = "Data_Set_ID")
    protected List<String> dataSetID;
    @XmlElement(name = "Personnel", required = true)
    protected List<Personnel> personnel;

    /**
     * Gets the value of the dataCenterName property.
     * 
     * @return
     *     possible object is
     *     {@link DataCenterName }
     *     
     */
    public DataCenterName getDataCenterName() {
        return dataCenterName;
    }

    /**
     * Sets the value of the dataCenterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCenterName }
     *     
     */
    public void setDataCenterName(DataCenterName value) {
        this.dataCenterName = value;
    }

    /**
     * Gets the value of the dataCenterURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCenterURL() {
        return dataCenterURL;
    }

    /**
     * Sets the value of the dataCenterURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCenterURL(String value) {
        this.dataCenterURL = value;
    }

    /**
     * Gets the value of the dataSetID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataSetID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataSetID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDataSetID() {
        if (dataSetID == null) {
            dataSetID = new ArrayList<String>();
        }
        return this.dataSetID;
    }

    /**
     * Gets the value of the personnel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonnel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Personnel }
     * 
     * 
     */
    public List<Personnel> getPersonnel() {
        if (personnel == null) {
            personnel = new ArrayList<Personnel>();
        }
        return this.personnel;
    }

}
