/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 01:56:59 PM PDT 
//

package org.esipfed.eskg.structures;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Discipline_Name"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Subdiscipline" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Detailed_Subdiscipline" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "disciplineName",
    "subdiscipline",
    "detailedSubdiscipline"
})
@XmlRootElement(name = "Discipline")
public class Discipline {

    @XmlElement(name = "Discipline_Name", required = true)
    protected String disciplineName;
    @XmlElement(name = "Subdiscipline")
    protected String subdiscipline;
    @XmlElement(name = "Detailed_Subdiscipline")
    protected String detailedSubdiscipline;

    /**
     * Gets the value of the disciplineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisciplineName() {
        return disciplineName;
    }

    /**
     * Sets the value of the disciplineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisciplineName(String value) {
        this.disciplineName = value;
    }

    /**
     * Gets the value of the subdiscipline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdiscipline() {
        return subdiscipline;
    }

    /**
     * Sets the value of the subdiscipline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdiscipline(String value) {
        this.subdiscipline = value;
    }

    /**
     * Gets the value of the detailedSubdiscipline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailedSubdiscipline() {
        return detailedSubdiscipline;
    }

    /**
     * Sets the value of the detailedSubdiscipline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailedSubdiscipline(String value) {
        this.detailedSubdiscipline = value;
    }

}
