/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 01:56:59 PM PDT 
//

package org.esipfed.eskg.structures;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nasa.gsfc.gcmd.aboutus.xml.dif package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EntryID_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Entry_ID");
    private final static QName _EntryTitle_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Entry_Title");
    private final static QName _DatasetCreator_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Dataset_Creator");
    private final static QName _DatasetTitle_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Dataset_Title");
    private final static QName _DatasetSeriesName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Dataset_Series_Name");
    private final static QName _DatasetReleaseDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Dataset_Release_Date");
    private final static QName _DatasetReleasePlace_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Dataset_Release_Place");
    private final static QName _DatasetPublisher_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Dataset_Publisher");
    private final static QName _Version_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Version");
    private final static QName _IssueIdentification_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Issue_Identification");
    private final static QName _DataPresentationForm_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Data_Presentation_Form");
    private final static QName _OtherCitationDetails_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Other_Citation_Details");
    private final static QName _OnlineResource_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Online_Resource");
    private final static QName _Role_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Role");
    private final static QName _FirstName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "First_Name");
    private final static QName _MiddleName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Middle_Name");
    private final static QName _LastName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Last_Name");
    private final static QName _Email_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Email");
    private final static QName _Phone_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Phone");
    private final static QName _Fax_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Fax");
    private final static QName _Address_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Address");
    private final static QName _City_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "City");
    private final static QName _ProvinceOrState_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Province_or_State");
    private final static QName _PostalCode_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Postal_Code");
    private final static QName _Country_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Country");
    private final static QName _DisciplineName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Discipline_Name");
    private final static QName _Subdiscipline_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Subdiscipline");
    private final static QName _DetailedSubdiscipline_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Detailed_Subdiscipline");
    private final static QName _Category_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Category");
    private final static QName _Topic_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Topic");
    private final static QName _Term_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Term");
    private final static QName _VariableLevel1_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Variable_Level_1");
    private final static QName _VariableLevel2_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Variable_Level_2");
    private final static QName _VariableLevel3_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Variable_Level_3");
    private final static QName _DetailedVariable_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Detailed_Variable");
    private final static QName _ISOTopicCategory_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "ISO_Topic_Category");
    private final static QName _Keyword_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Keyword");
    private final static QName _ShortName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Short_Name");
    private final static QName _LongName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Long_Name");
    private final static QName _StartDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Start_Date");
    private final static QName _StopDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Stop_Date");
    private final static QName _PaleoStartDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Paleo_Start_Date");
    private final static QName _PaleoStopDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Paleo_Stop_Date");
    private final static QName _Eon_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Eon");
    private final static QName _Era_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Era");
    private final static QName _Period_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Period");
    private final static QName _Epoch_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Epoch");
    private final static QName _Stage_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Stage");
    private final static QName _DetailedClassification_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Detailed_Classification");
    private final static QName _DataSetProgress_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Data_Set_Progress");
    private final static QName _SouthernmostLatitude_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Southernmost_Latitude");
    private final static QName _NorthernmostLatitude_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Northernmost_Latitude");
    private final static QName _WesternmostLongitude_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Westernmost_Longitude");
    private final static QName _EasternmostLongitude_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Easternmost_Longitude");
    private final static QName _MinimumAltitude_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Minimum_Altitude");
    private final static QName _MaximumAltitude_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Maximum_Altitude");
    private final static QName _MinimumDepth_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Minimum_Depth");
    private final static QName _MaximumDepth_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Maximum_Depth");
    private final static QName _LocationCategory_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Location_Category");
    private final static QName _LocationType_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Location_Type");
    private final static QName _LocationSubregion1_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Location_Subregion1");
    private final static QName _LocationSubregion2_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Location_Subregion2");
    private final static QName _LocationSubregion3_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Location_Subregion3");
    private final static QName _DetailedLocation_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Detailed_Location");
    private final static QName _LatitudeResolution_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Latitude_Resolution");
    private final static QName _LongitudeResolution_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Longitude_Resolution");
    private final static QName _HorizontalResolutionRange_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Horizontal_Resolution_Range");
    private final static QName _VerticalResolution_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Vertical_Resolution");
    private final static QName _VerticalResolutionRange_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Vertical_Resolution_Range");
    private final static QName _TemporalResolution_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Temporal_Resolution");
    private final static QName _TemporalResolutionRange_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Temporal_Resolution_Range");
    private final static QName _Quality_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Quality");
    private final static QName _AccessConstraints_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Access_Constraints");
    private final static QName _UseConstraints_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Use_Constraints");
    private final static QName _DataSetLanguage_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Data_Set_Language");
    private final static QName _OriginatingCenter_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Originating_Center");
    private final static QName _DataCenterURL_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Data_Center_URL");
    private final static QName _DataSetID_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Data_Set_ID");
    private final static QName _DistributionMedia_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Distribution_Media");
    private final static QName _DistributionSize_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Distribution_Size");
    private final static QName _DistributionFormat_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Distribution_Format");
    private final static QName _Fees_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Fees");
    private final static QName _File_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "File");
    private final static QName _URL_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "URL");
    private final static QName _Format_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Format");
    private final static QName _Caption_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Caption");
    private final static QName _Description_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Description");
    private final static QName _Author_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Author");
    private final static QName _PublicationDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Publication_Date");
    private final static QName _Title_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Title");
    private final static QName _Series_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Series");
    private final static QName _Edition_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Edition");
    private final static QName _Volume_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Volume");
    private final static QName _Issue_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Issue");
    private final static QName _ReportNumber_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Report_Number");
    private final static QName _PublicationPlace_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Publication_Place");
    private final static QName _Publisher_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Publisher");
    private final static QName _Pages_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Pages");
    private final static QName _ISBN_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "ISBN");
    private final static QName _DOI_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "DOI");
    private final static QName _OtherReferenceDetails_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Other_Reference_Details");
    private final static QName _Abstract_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Abstract");
    private final static QName _Purpose_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Purpose");
    private final static QName _Type_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Type");
    private final static QName _Subtype_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Subtype");
    private final static QName _ParentDIF_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Parent_DIF");
    private final static QName _OriginatingMetadataNode_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Originating_Metadata_Node");
    private final static QName _MetadataName_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Metadata_Name");
    private final static QName _MetadataVersion_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Metadata_Version");
    private final static QName _DIFCreationDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "DIF_Creation_Date");
    private final static QName _LastDIFRevisionDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Last_DIF_Revision_Date");
    private final static QName _DIFRevisionHistory_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "DIF_Revision_History");
    private final static QName _FutureDIFReviewDate_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Future_DIF_Review_Date");
    private final static QName _Private_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "Private");
    private final static QName _FAX_QNAME = new QName("http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", "FAX");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nasa.gsfc.gcmd.aboutus.xml.dif
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DIF }
     * 
     */
    public DIF createDIF() {
        return new DIF();
    }

    /**
     * Create an instance of {@link DataSetCitation }
     * 
     */
    public DataSetCitation createDataSetCitation() {
        return new DataSetCitation();
    }

    /**
     * Create an instance of {@link Personnel }
     * 
     */
    public Personnel createPersonnel() {
        return new Personnel();
    }

    /**
     * Create an instance of {@link ContactAddress }
     * 
     */
    public ContactAddress createContactAddress() {
        return new ContactAddress();
    }

    /**
     * Create an instance of {@link Discipline }
     * 
     */
    public Discipline createDiscipline() {
        return new Discipline();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link SensorName }
     * 
     */
    public SensorName createSensorName() {
        return new SensorName();
    }

    /**
     * Create an instance of {@link SourceName }
     * 
     */
    public SourceName createSourceName() {
        return new SourceName();
    }

    /**
     * Create an instance of {@link TemporalCoverage }
     * 
     */
    public TemporalCoverage createTemporalCoverage() {
        return new TemporalCoverage();
    }

    /**
     * Create an instance of {@link PaleoTemporalCoverage }
     * 
     */
    public PaleoTemporalCoverage createPaleoTemporalCoverage() {
        return new PaleoTemporalCoverage();
    }

    /**
     * Create an instance of {@link ChronostratigraphicUnit }
     * 
     */
    public ChronostratigraphicUnit createChronostratigraphicUnit() {
        return new ChronostratigraphicUnit();
    }

    /**
     * Create an instance of {@link SpatialCoverage }
     * 
     */
    public SpatialCoverage createSpatialCoverage() {
        return new SpatialCoverage();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link DataResolution }
     * 
     */
    public DataResolution createDataResolution() {
        return new DataResolution();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link DataCenter }
     * 
     */
    public DataCenter createDataCenter() {
        return new DataCenter();
    }

    /**
     * Create an instance of {@link DataCenterName }
     * 
     */
    public DataCenterName createDataCenterName() {
        return new DataCenterName();
    }

    /**
     * Create an instance of {@link Distribution }
     * 
     */
    public Distribution createDistribution() {
        return new Distribution();
    }

    /**
     * Create an instance of {@link MultimediaSample }
     * 
     */
    public MultimediaSample createMultimediaSample() {
        return new MultimediaSample();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Summary }
     * 
     */
    public Summary createSummary() {
        return new Summary();
    }

    /**
     * Create an instance of {@link RelatedURL }
     * 
     */
    public RelatedURL createRelatedURL() {
        return new RelatedURL();
    }

    /**
     * Create an instance of {@link URLContentType }
     * 
     */
    public URLContentType createURLContentType() {
        return new URLContentType();
    }

    /**
     * Create an instance of {@link IDNNode }
     * 
     */
    public IDNNode createIDNNode() {
        return new IDNNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Entry_ID")
    public JAXBElement<String> createEntryID(String value) {
        return new JAXBElement<String>(_EntryID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Entry_Title")
    public JAXBElement<String> createEntryTitle(String value) {
        return new JAXBElement<String>(_EntryTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Dataset_Creator")
    public JAXBElement<String> createDatasetCreator(String value) {
        return new JAXBElement<String>(_DatasetCreator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Dataset_Title")
    public JAXBElement<String> createDatasetTitle(String value) {
        return new JAXBElement<String>(_DatasetTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Dataset_Series_Name")
    public JAXBElement<String> createDatasetSeriesName(String value) {
        return new JAXBElement<String>(_DatasetSeriesName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Dataset_Release_Date")
    public JAXBElement<String> createDatasetReleaseDate(String value) {
        return new JAXBElement<String>(_DatasetReleaseDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Dataset_Release_Place")
    public JAXBElement<String> createDatasetReleasePlace(String value) {
        return new JAXBElement<String>(_DatasetReleasePlace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Dataset_Publisher")
    public JAXBElement<String> createDatasetPublisher(String value) {
        return new JAXBElement<String>(_DatasetPublisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Issue_Identification")
    public JAXBElement<String> createIssueIdentification(String value) {
        return new JAXBElement<String>(_IssueIdentification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Data_Presentation_Form")
    public JAXBElement<String> createDataPresentationForm(String value) {
        return new JAXBElement<String>(_DataPresentationForm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Other_Citation_Details")
    public JAXBElement<String> createOtherCitationDetails(String value) {
        return new JAXBElement<String>(_OtherCitationDetails_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Online_Resource")
    public JAXBElement<String> createOnlineResource(String value) {
        return new JAXBElement<String>(_OnlineResource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Role")
    public JAXBElement<String> createRole(String value) {
        return new JAXBElement<String>(_Role_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "First_Name")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Middle_Name")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Last_Name")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Phone")
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Fax")
    public JAXBElement<String> createFax(String value) {
        return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Province_or_State")
    public JAXBElement<String> createProvinceOrState(String value) {
        return new JAXBElement<String>(_ProvinceOrState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Postal_Code")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Discipline_Name")
    public JAXBElement<String> createDisciplineName(String value) {
        return new JAXBElement<String>(_DisciplineName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Subdiscipline")
    public JAXBElement<String> createSubdiscipline(String value) {
        return new JAXBElement<String>(_Subdiscipline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Detailed_Subdiscipline")
    public JAXBElement<String> createDetailedSubdiscipline(String value) {
        return new JAXBElement<String>(_DetailedSubdiscipline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<String>(_Category_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Topic")
    public JAXBElement<String> createTopic(String value) {
        return new JAXBElement<String>(_Topic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Term")
    public JAXBElement<String> createTerm(String value) {
        return new JAXBElement<String>(_Term_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Variable_Level_1")
    public JAXBElement<String> createVariableLevel1(String value) {
        return new JAXBElement<String>(_VariableLevel1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Variable_Level_2")
    public JAXBElement<String> createVariableLevel2(String value) {
        return new JAXBElement<String>(_VariableLevel2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Variable_Level_3")
    public JAXBElement<String> createVariableLevel3(String value) {
        return new JAXBElement<String>(_VariableLevel3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Detailed_Variable")
    public JAXBElement<String> createDetailedVariable(String value) {
        return new JAXBElement<String>(_DetailedVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "ISO_Topic_Category")
    public JAXBElement<String> createISOTopicCategory(String value) {
        return new JAXBElement<String>(_ISOTopicCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Keyword")
    public JAXBElement<String> createKeyword(String value) {
        return new JAXBElement<String>(_Keyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Short_Name")
    public JAXBElement<String> createShortName(String value) {
        return new JAXBElement<String>(_ShortName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Long_Name")
    public JAXBElement<String> createLongName(String value) {
        return new JAXBElement<String>(_LongName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Start_Date")
    public JAXBElement<String> createStartDate(String value) {
        return new JAXBElement<String>(_StartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Stop_Date")
    public JAXBElement<String> createStopDate(String value) {
        return new JAXBElement<String>(_StopDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Paleo_Start_Date")
    public JAXBElement<String> createPaleoStartDate(String value) {
        return new JAXBElement<String>(_PaleoStartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Paleo_Stop_Date")
    public JAXBElement<String> createPaleoStopDate(String value) {
        return new JAXBElement<String>(_PaleoStopDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Eon")
    public JAXBElement<String> createEon(String value) {
        return new JAXBElement<String>(_Eon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Era")
    public JAXBElement<String> createEra(String value) {
        return new JAXBElement<String>(_Era_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Period")
    public JAXBElement<String> createPeriod(String value) {
        return new JAXBElement<String>(_Period_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Epoch")
    public JAXBElement<String> createEpoch(String value) {
        return new JAXBElement<String>(_Epoch_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Stage")
    public JAXBElement<String> createStage(String value) {
        return new JAXBElement<String>(_Stage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Detailed_Classification")
    public JAXBElement<String> createDetailedClassification(String value) {
        return new JAXBElement<String>(_DetailedClassification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Data_Set_Progress")
    public JAXBElement<String> createDataSetProgress(String value) {
        return new JAXBElement<String>(_DataSetProgress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Southernmost_Latitude")
    public JAXBElement<String> createSouthernmostLatitude(String value) {
        return new JAXBElement<String>(_SouthernmostLatitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Northernmost_Latitude")
    public JAXBElement<String> createNorthernmostLatitude(String value) {
        return new JAXBElement<String>(_NorthernmostLatitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Westernmost_Longitude")
    public JAXBElement<String> createWesternmostLongitude(String value) {
        return new JAXBElement<String>(_WesternmostLongitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Easternmost_Longitude")
    public JAXBElement<String> createEasternmostLongitude(String value) {
        return new JAXBElement<String>(_EasternmostLongitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Minimum_Altitude")
    public JAXBElement<String> createMinimumAltitude(String value) {
        return new JAXBElement<String>(_MinimumAltitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Maximum_Altitude")
    public JAXBElement<String> createMaximumAltitude(String value) {
        return new JAXBElement<String>(_MaximumAltitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Minimum_Depth")
    public JAXBElement<String> createMinimumDepth(String value) {
        return new JAXBElement<String>(_MinimumDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Maximum_Depth")
    public JAXBElement<String> createMaximumDepth(String value) {
        return new JAXBElement<String>(_MaximumDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Location_Category")
    public JAXBElement<String> createLocationCategory(String value) {
        return new JAXBElement<String>(_LocationCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Location_Type")
    public JAXBElement<String> createLocationType(String value) {
        return new JAXBElement<String>(_LocationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Location_Subregion1")
    public JAXBElement<String> createLocationSubregion1(String value) {
        return new JAXBElement<String>(_LocationSubregion1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Location_Subregion2")
    public JAXBElement<String> createLocationSubregion2(String value) {
        return new JAXBElement<String>(_LocationSubregion2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Location_Subregion3")
    public JAXBElement<String> createLocationSubregion3(String value) {
        return new JAXBElement<String>(_LocationSubregion3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Detailed_Location")
    public JAXBElement<String> createDetailedLocation(String value) {
        return new JAXBElement<String>(_DetailedLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Latitude_Resolution")
    public JAXBElement<String> createLatitudeResolution(String value) {
        return new JAXBElement<String>(_LatitudeResolution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Longitude_Resolution")
    public JAXBElement<String> createLongitudeResolution(String value) {
        return new JAXBElement<String>(_LongitudeResolution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Horizontal_Resolution_Range")
    public JAXBElement<String> createHorizontalResolutionRange(String value) {
        return new JAXBElement<String>(_HorizontalResolutionRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Vertical_Resolution")
    public JAXBElement<String> createVerticalResolution(String value) {
        return new JAXBElement<String>(_VerticalResolution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Vertical_Resolution_Range")
    public JAXBElement<String> createVerticalResolutionRange(String value) {
        return new JAXBElement<String>(_VerticalResolutionRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Temporal_Resolution")
    public JAXBElement<String> createTemporalResolution(String value) {
        return new JAXBElement<String>(_TemporalResolution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Temporal_Resolution_Range")
    public JAXBElement<String> createTemporalResolutionRange(String value) {
        return new JAXBElement<String>(_TemporalResolutionRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Quality")
    public JAXBElement<String> createQuality(String value) {
        return new JAXBElement<String>(_Quality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Access_Constraints")
    public JAXBElement<String> createAccessConstraints(String value) {
        return new JAXBElement<String>(_AccessConstraints_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Use_Constraints")
    public JAXBElement<String> createUseConstraints(String value) {
        return new JAXBElement<String>(_UseConstraints_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Data_Set_Language")
    public JAXBElement<String> createDataSetLanguage(String value) {
        return new JAXBElement<String>(_DataSetLanguage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Originating_Center")
    public JAXBElement<String> createOriginatingCenter(String value) {
        return new JAXBElement<String>(_OriginatingCenter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Data_Center_URL")
    public JAXBElement<String> createDataCenterURL(String value) {
        return new JAXBElement<String>(_DataCenterURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Data_Set_ID")
    public JAXBElement<String> createDataSetID(String value) {
        return new JAXBElement<String>(_DataSetID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Distribution_Media")
    public JAXBElement<String> createDistributionMedia(String value) {
        return new JAXBElement<String>(_DistributionMedia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Distribution_Size")
    public JAXBElement<String> createDistributionSize(String value) {
        return new JAXBElement<String>(_DistributionSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Distribution_Format")
    public JAXBElement<String> createDistributionFormat(String value) {
        return new JAXBElement<String>(_DistributionFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Fees")
    public JAXBElement<String> createFees(String value) {
        return new JAXBElement<String>(_Fees_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "File")
    public JAXBElement<String> createFile(String value) {
        return new JAXBElement<String>(_File_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Format")
    public JAXBElement<String> createFormat(String value) {
        return new JAXBElement<String>(_Format_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Caption")
    public JAXBElement<String> createCaption(String value) {
        return new JAXBElement<String>(_Caption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Publication_Date")
    public JAXBElement<String> createPublicationDate(String value) {
        return new JAXBElement<String>(_PublicationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Series")
    public JAXBElement<String> createSeries(String value) {
        return new JAXBElement<String>(_Series_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Edition")
    public JAXBElement<String> createEdition(String value) {
        return new JAXBElement<String>(_Edition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Volume")
    public JAXBElement<String> createVolume(String value) {
        return new JAXBElement<String>(_Volume_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Issue")
    public JAXBElement<String> createIssue(String value) {
        return new JAXBElement<String>(_Issue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Report_Number")
    public JAXBElement<String> createReportNumber(String value) {
        return new JAXBElement<String>(_ReportNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Publication_Place")
    public JAXBElement<String> createPublicationPlace(String value) {
        return new JAXBElement<String>(_PublicationPlace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Publisher")
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<String>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Pages")
    public JAXBElement<String> createPages(String value) {
        return new JAXBElement<String>(_Pages_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "ISBN")
    public JAXBElement<String> createISBN(String value) {
        return new JAXBElement<String>(_ISBN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "DOI")
    public JAXBElement<String> createDOI(String value) {
        return new JAXBElement<String>(_DOI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Other_Reference_Details")
    public JAXBElement<String> createOtherReferenceDetails(String value) {
        return new JAXBElement<String>(_OtherReferenceDetails_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Abstract")
    public JAXBElement<String> createAbstract(String value) {
        return new JAXBElement<String>(_Abstract_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Purpose")
    public JAXBElement<String> createPurpose(String value) {
        return new JAXBElement<String>(_Purpose_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Subtype")
    public JAXBElement<String> createSubtype(String value) {
        return new JAXBElement<String>(_Subtype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Parent_DIF")
    public JAXBElement<String> createParentDIF(String value) {
        return new JAXBElement<String>(_ParentDIF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Originating_Metadata_Node")
    public JAXBElement<String> createOriginatingMetadataNode(String value) {
        return new JAXBElement<String>(_OriginatingMetadataNode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Metadata_Name")
    public JAXBElement<String> createMetadataName(String value) {
        return new JAXBElement<String>(_MetadataName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Metadata_Version")
    public JAXBElement<String> createMetadataVersion(String value) {
        return new JAXBElement<String>(_MetadataVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "DIF_Creation_Date")
    public JAXBElement<String> createDIFCreationDate(String value) {
        return new JAXBElement<String>(_DIFCreationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Last_DIF_Revision_Date")
    public JAXBElement<String> createLastDIFRevisionDate(String value) {
        return new JAXBElement<String>(_LastDIFRevisionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "DIF_Revision_History")
    public JAXBElement<String> createDIFRevisionHistory(String value) {
        return new JAXBElement<String>(_DIFRevisionHistory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Future_DIF_Review_Date")
    public JAXBElement<String> createFutureDIFReviewDate(String value) {
        return new JAXBElement<String>(_FutureDIFReviewDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "Private")
    public JAXBElement<String> createPrivate(String value) {
        return new JAXBElement<String>(_Private_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", name = "FAX")
    public JAXBElement<String> createFAX(String value) {
        return new JAXBElement<String>(_FAX_QNAME, String.class, null, value);
    }

}
