/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 01:56:59 PM PDT 
//

package org.esipfed.eskg.structures;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Author" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Publication_Date" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Title" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Series" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Edition" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Volume" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Issue" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Report_Number" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Publication_Place" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Publisher" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Pages" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}ISBN" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}DOI" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Online_Resource" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Other_Reference_Details" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Reference")
public class Reference {

    @XmlElementRefs({
        @XmlElementRef(name = "Publication_Place", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ISBN", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Title", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Issue", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Publication_Date", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Report_Number", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Publisher", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Pages", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Other_Reference_Details", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DOI", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Author", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Series", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Online_Resource", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Volume", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Edition", namespace = "http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
