/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 01:56:59 PM PDT 
//

package org.esipfed.eskg.structures;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Southernmost_Latitude" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Northernmost_Latitude" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Westernmost_Longitude" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Easternmost_Longitude" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Minimum_Altitude" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Maximum_Altitude" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Minimum_Depth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/}Maximum_Depth" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "southernmostLatitude",
    "northernmostLatitude",
    "westernmostLongitude",
    "easternmostLongitude",
    "minimumAltitude",
    "maximumAltitude",
    "minimumDepth",
    "maximumDepth"
})
@XmlRootElement(name = "Spatial_Coverage")
public class SpatialCoverage {

    @XmlElement(name = "Southernmost_Latitude")
    protected String southernmostLatitude;
    @XmlElement(name = "Northernmost_Latitude")
    protected String northernmostLatitude;
    @XmlElement(name = "Westernmost_Longitude")
    protected String westernmostLongitude;
    @XmlElement(name = "Easternmost_Longitude")
    protected String easternmostLongitude;
    @XmlElement(name = "Minimum_Altitude")
    protected String minimumAltitude;
    @XmlElement(name = "Maximum_Altitude")
    protected String maximumAltitude;
    @XmlElement(name = "Minimum_Depth")
    protected String minimumDepth;
    @XmlElement(name = "Maximum_Depth")
    protected String maximumDepth;

    /**
     * Gets the value of the southernmostLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSouthernmostLatitude() {
        return southernmostLatitude;
    }

    /**
     * Sets the value of the southernmostLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSouthernmostLatitude(String value) {
        this.southernmostLatitude = value;
    }

    /**
     * Gets the value of the northernmostLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNorthernmostLatitude() {
        return northernmostLatitude;
    }

    /**
     * Sets the value of the northernmostLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNorthernmostLatitude(String value) {
        this.northernmostLatitude = value;
    }

    /**
     * Gets the value of the westernmostLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWesternmostLongitude() {
        return westernmostLongitude;
    }

    /**
     * Sets the value of the westernmostLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWesternmostLongitude(String value) {
        this.westernmostLongitude = value;
    }

    /**
     * Gets the value of the easternmostLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEasternmostLongitude() {
        return easternmostLongitude;
    }

    /**
     * Sets the value of the easternmostLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEasternmostLongitude(String value) {
        this.easternmostLongitude = value;
    }

    /**
     * Gets the value of the minimumAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumAltitude() {
        return minimumAltitude;
    }

    /**
     * Sets the value of the minimumAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumAltitude(String value) {
        this.minimumAltitude = value;
    }

    /**
     * Gets the value of the maximumAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumAltitude() {
        return maximumAltitude;
    }

    /**
     * Sets the value of the maximumAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumAltitude(String value) {
        this.maximumAltitude = value;
    }

    /**
     * Gets the value of the minimumDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumDepth() {
        return minimumDepth;
    }

    /**
     * Sets the value of the minimumDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumDepth(String value) {
        this.minimumDepth = value;
    }

    /**
     * Gets the value of the maximumDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumDepth() {
        return maximumDepth;
    }

    /**
     * Sets the value of the maximumDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumDepth(String value) {
        this.maximumDepth = value;
    }

}
